### ISSUE TITLE
mailprog param commented in slurm.conf template

### ISSUE THREAD

**Issue by stevca9** [ULHPC/puppet-slurm#10]
The file templates/slurm.conf.erb currently has the MailProg option commented out so the parameter mailprog in not utilized in slurm.conf

`#MailProg=<%= scope['slurm::mailprog'] %>`

**Comment by Falkor** [comment]
you can give a try to the 66cd8e5 commit of the `devel` branch -- if that's fine, I'll add it to the next release of the module.

**Comment by stevca9** [comment]
The # has been removed in slurm.conf and the option is being correctly read. Thank you for resolving this so quickly!
