### ISSUE TITLE
Please add parameters for slurm.conf

### ISSUE THREAD

**Issue by stevca9** [ULHPC/puppet-slurm#11]
Please add the following parameters to params.pp and include them in templates/slurm.conf.erb

ResvOverRun
SlurmctldTimeout
SlurmdTimeout
PriorityFavorSmall
PriorityMaxAge
PriorityUsageResetPeriod

I would like to request the above parameters. Thank you!

**Comment by Falkor** [comment]
you can give a try to the 66cd8e5 commit of the `devel` branch -- if that's fine, I'll add it to the next release of the module.

**Comment by stevca9** [comment]
I was able to successfully add these parameters and use them in slurm.conf. Thank you for adding these so quickly!
