### ISSUE TITLE
slurmdbd on separate host

### ISSUE THREAD

**Issue by uvNikita** [ULHPC/puppet-slurm#2]
It seems like in the current implementation of the module `slurmdbd` and `slurmctld` have to be on the same host. In particular, `AccountingStorageHost` is set to the current control host in the `slurm.conf`.
https://github.com/ULHPC/puppet-slurm/blob/c5782ed1e778e8e2b8833968903517af0e1b399e/templates/slurm.conf.erb#L206

It seems that just using db host instead should fix the problem (note that I didn't actually test that):
```
AccountingStorageHost=<%= scope['slurm::slurmdbd::dbdhost'] %>
```

I don't know much about slurm yet, so correct me please if I'm missing something.

**Comment by Falkor** [comment]
Indeed, our current setup makes `slurmdbd` and `slurmctld` run on the same host. 
We'll see for a new release of the module allowing for these changes, probably according to your suggestion.

**Comment by uvNikita** [comment]
OK, thank you for the confirmation.
