### ISSUE TITLE
SchedMD source archive no longer available

### ISSUE THREAD

**Issue by Rovanion** [ULHPC/puppet-slurm#27]
The class `::slurm` has a parameter `src_archived` which when set to true tries to download the source package from https://www.schedmd.com/downloads/archive/, for example https://www.schedmd.com/downloads/archive/slurm-16.05.10.tar.bz2. These URL:s no longer seem valid and the switch should probably be removed or the URL updated to become valid again.

**Comment by Falkor** [comment]
Thanks for checking (and providing the associated code update)
