### ISSUE TITLE
Replace svarrette/ulimit dependency with saz/limits

### ISSUE THREAD

**Issue by westbywest** [ULHPC/puppet-slurm#48]
The class slurm::slurmd has a dependency on the svarrette/ulimit module which isn't listed among dependencies in README.md.

That ulimit module hasn't been updated in 3 years, and its Readme on Forge states that module may be removed if the one it was forked from is updated.

Consider switching to saz/limits module?  It's functionally equivalent, and it also is in much broader use than svarrette's.

**Comment by Falkor** [comment]
Yes, you're fully right, we'll revert to the default module provided by saz
