### ISSUE TITLE
mysql module version 14.0.0 breaks slurmdbd.pp

### ISSUE THREAD

**Issue by trenta** [ULHPC/puppet-slurm#65]
After upgrading puppetlabs mysql module to version 14.0.0 we get the following error.

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, wrong number of arguments (given 2, expected 1) (file: /etc/puppetlabs/code/environments/production/modules/slurm/manifests/slurmdbd.pp, line: 251, column: 26) on node test-sc01.svi.edu.au
```

**Comment by kaatmanduu** [comment]
12.0.3 will work. 13.3.0 throws a Error: Failed to apply catalog: Parameter command failed on Exec[wait_for_mysql_socket_to_open]: Command must be a String, got value of class Array .... message. It would be helpful to at least mention the version requirements someplace to avoid confusion.
