### ISSUE TITLE
Allow to change MySQL datadir

### ISSUE THREAD

**Issue by uvNikita** [ULHPC/puppet-slurm#9]
In our setup, we have to change MySQL data directory from the default one. Previously, it was possible to use something like this:
```
class { '::mysql::server':
  override_options => {
    'mysqld' => {
      'datadir' => "/data/mysql",
    }
  },
}
```
But after this commit https://github.com/ULHPC/puppet-slurm/commit/a5fa6f01a4bf5e4f3bb8242c5779b97c54d6b162 puppet fails with `Duplicate declaration` error.

Do you have any advice on how we can set the data directory now? Maybe it is possible to add `datadir` option to this module, or something like `manage_mysql` to leave `::mysql::server` declaration to a user?

**Comment by Falkor** [comment]
the `manage_mysql` may be the best way, and/or with a hash parameter for the override_options, I'll think of it -- the commit a5fa6f0 was required on our side to prevent the systematic restart of the mysql server.

**Comment by Falkor** [comment]
Still not easy to provide. 
I thus close the issue as I won't find time to implement it. Sorry for the inconvenience.
